site_name: MOS-9
site_description: 开源机器人MOS-9，涵盖机械设计、电路系统、通信框架、运动控制、仿真与模型、教程和开发参考
site_url: https://yourname.github.io/open-robot-docs/
repo_url: https://github.com/yourname/open-robot-docs
repo_name: yourname/open-robot-docs
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.action.view

  palette:
    - scheme: default
      primary: blue
      accent: blue

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourname/open-robot-docs

nav:
  - 首页: index.md
  - 项目背景: robocup_intro.md

  - 系统总览:
      - 总体架构: overview/architecture.md

  - 机械设计:
      - 概览: mechanical/index.md
      - 构型设计: mechanical/body-structure.md
      - 电机选型: mechanical/motor_selection.md
      - 结构件设计: mechanical/link_design.md
      - 材料与加工: mechanical/materials.md

  - 电气系统:
      - 概览: electronics/index.md
      - 电路设计及PCB制作: electronics/circuit_design.md

  - 通信系统:
      - 概览: communication/index.md
      - 电机通讯: communication/motor_communication.md
      - 进程间通讯: communication/robot_ipc.md
      - Robot IPC实现: communication/robot_ipc_framework.md

  - 仿真模型与数据:
      - 概览: simulation/index.md
      - URDF: simulation/urdf.md
      - XML和USD: simulation/xml_usd.md
      - 运动重定向: simulation/retarget.md

  - 运动控制:
      - 概览: control/index.md
      - AMP: control/amp.md
      - Mimic: control/mimic.md
      - 电机系统辨识: control/system_identification.md
      - Sim2Real: control/sim2real.md


  - 开发指南:
      - 环境配置: development/setup.md
      - 测试: development/testing.md

  - 结语: conclusion.md

  - FAQ:
      - 概览: faq/index.md